# Generated by Django 4.2.10 on 2024-03-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='areaName',
            new_name='companyName',
        ),
    ]
